class Movie {
  String datum;
  String nazivFilma;
  String engleskiNazivFilma;
  String redatelj;
  String scenarist;
  String snimatelj;
  String montazer;
  String producent;
  String nazivProdukcije;
  String zemljaProdukcije;
  String zemljaProdukcijeEN;
  String zemljaKoprodukcije1;
  String zemljaKoprodukcije2;
  String zemljaKoprodukcije3;
  String nazivKoprodukcija;
  int godinaProizvodnje;
  String trajanje;
  String forspanFilma;
  String webFilma;
  String korisnickoImeFilma;
  String lozinkaFilma;
  String kratkiSinopsis;
  String kratkiSinopsisEN;
  String sudjelovanjeNaFestivalu1;
  String sudjelovanjeNaFestivalu2;
  String sudjelovanjeNaFestivalu3;
  String sudjelovanjeNaFestivalu4;
  String sudjelovanjeNaFestivalu5;
  String nagradePriznanja1;
  String nagradePriznanja2;
  String nagradePriznanja3;
  String nagradePriznanja4;
  String nagradePriznanja5;
  String biografijaRedatelja;
  String filmografijaRedatelja;
  String kontaktImePrezime;
  String kontaktProdukcija;
  String kontaktTelefon;
  String kontaktMobitel;
  String kontaktFax;
  String kontaktMail;
  String kontaktWebProdukcija;
  String iP;
  int iD;
  bool pogledan;
  bool odabran;
  bool zanimljiv;
  String komentarSelektora;
  String festivaliNagrade;
  String festivaliNagradeEN;
  String videoIFrame;
  String danPrikazivanja;
  String redniBrojPrikazivanja;
  String fotografija;
  int kategorijaID;
  bool konkurencija;
  String forspanIFrame;

  Movie.fromJson(Map<String, dynamic> json) {
    datum = json['Datum'];
    nazivFilma = json['NazivFilma'];
    engleskiNazivFilma = json['EngleskiNazivFilma'];
    redatelj = json['Redatelj'];
    scenarist = json['Scenarist'];
    snimatelj = json['Snimatelj'];
    montazer = json['Montazer'];
    producent = json['Producent'];
    nazivProdukcije = json['NazivProdukcije'];
    zemljaProdukcije = json['ZemljaProdukcije'];
    zemljaProdukcijeEN = json['ZemljaProdukcijeEN'];
    zemljaKoprodukcije1 = json['ZemljaKoprodukcije1'];
    zemljaKoprodukcije2 = json['ZemljaKoprodukcije2'];
    zemljaKoprodukcije3 = json['ZemljaKoprodukcije3'];
    nazivKoprodukcija = json['NazivKoprodukcija'];
    godinaProizvodnje = json['GodinaProizvodnje'];
    trajanje = json['Trajanje'];
    forspanFilma = json['ForspanFilma'];
    webFilma = json['WebFilma'];
    korisnickoImeFilma = json['KorisnickoImeFilma'];
    lozinkaFilma = json['LozinkaFilma'];
    kratkiSinopsis = json['KratkiSinopsis'];
    kratkiSinopsisEN = json['KratkiSinopsisEN'];
    sudjelovanjeNaFestivalu1 = json['SudjelovanjeNaFestivalu1'];
    sudjelovanjeNaFestivalu2 = json['SudjelovanjeNaFestivalu2'];
    sudjelovanjeNaFestivalu3 = json['SudjelovanjeNaFestivalu3'];
    sudjelovanjeNaFestivalu4 = json['SudjelovanjeNaFestivalu4'];
    sudjelovanjeNaFestivalu5 = json['SudjelovanjeNaFestivalu5'];
    nagradePriznanja1 = json['NagradePriznanja1'];
    nagradePriznanja2 = json['NagradePriznanja2'];
    nagradePriznanja3 = json['NagradePriznanja3'];
    nagradePriznanja4 = json['NagradePriznanja4'];
    nagradePriznanja5 = json['NagradePriznanja5'];
    biografijaRedatelja = json['BiografijaRedatelja'];
    filmografijaRedatelja = json['FilmografijaRedatelja'];
    kontaktImePrezime = json['KontaktImePrezime'];
    kontaktProdukcija = json['KontaktProdukcija'];
    kontaktTelefon = json['KontaktTelefon'];
    kontaktMobitel = json['KontaktMobitel'];
    kontaktFax = json['KontaktFax'];
    kontaktMail = json['KontaktMail'];
    kontaktWebProdukcija = json['KontaktWebProdukcija'];
    iP = json['IP'];
    iD = json['ID'];
    pogledan = json['Pogledan'];
    odabran = json['Odabran'];
    zanimljiv = json['Zanimljiv'];
    komentarSelektora = json['KomentarSelektora'];
    festivaliNagrade = json['FestivaliNagrade'];
    festivaliNagradeEN = json['FestivaliNagradeEN'];
    videoIFrame = json['VideoIFrame'];
    danPrikazivanja = json['DanPrikazivanja'];
    redniBrojPrikazivanja = json['RedniBrojPrikazivanja'];
    fotografija = json['Fotografija'];
    kategorijaID = json['KategorijaID'];
    konkurencija = json['Konkurencija'];
    forspanIFrame = json['ForspanIFrame'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['Datum'] = this.datum;
    data['NazivFilma'] = this.nazivFilma;
    data['EngleskiNazivFilma'] = this.engleskiNazivFilma;
    data['Redatelj'] = this.redatelj;
    data['Scenarist'] = this.scenarist;
    data['Snimatelj'] = this.snimatelj;
    data['Montazer'] = this.montazer;
    data['Producent'] = this.producent;
    data['NazivProdukcije'] = this.nazivProdukcije;
    data['ZemljaProdukcije'] = this.zemljaProdukcije;
    data['ZemljaProdukcijeEN'] = this.zemljaProdukcijeEN;
    data['ZemljaKoprodukcije1'] = this.zemljaKoprodukcije1;
    data['ZemljaKoprodukcije2'] = this.zemljaKoprodukcije2;
    data['ZemljaKoprodukcije3'] = this.zemljaKoprodukcije3;
    data['NazivKoprodukcija'] = this.nazivKoprodukcija;
    data['GodinaProizvodnje'] = this.godinaProizvodnje;
    data['Trajanje'] = this.trajanje;
    data['ForspanFilma'] = this.forspanFilma;
    data['WebFilma'] = this.webFilma;
    data['KorisnickoImeFilma'] = this.korisnickoImeFilma;
    data['LozinkaFilma'] = this.lozinkaFilma;
    data['KratkiSinopsis'] = this.kratkiSinopsis;
    data['KratkiSinopsisEN'] = this.kratkiSinopsisEN;
    data['SudjelovanjeNaFestivalu1'] = this.sudjelovanjeNaFestivalu1;
    data['SudjelovanjeNaFestivalu2'] = this.sudjelovanjeNaFestivalu2;
    data['SudjelovanjeNaFestivalu3'] = this.sudjelovanjeNaFestivalu3;
    data['SudjelovanjeNaFestivalu4'] = this.sudjelovanjeNaFestivalu4;
    data['SudjelovanjeNaFestivalu5'] = this.sudjelovanjeNaFestivalu5;
    data['NagradePriznanja1'] = this.nagradePriznanja1;
    data['NagradePriznanja2'] = this.nagradePriznanja2;
    data['NagradePriznanja3'] = this.nagradePriznanja3;
    data['NagradePriznanja4'] = this.nagradePriznanja4;
    data['NagradePriznanja5'] = this.nagradePriznanja5;
    data['BiografijaRedatelja'] = this.biografijaRedatelja;
    data['FilmografijaRedatelja'] = this.filmografijaRedatelja;
    data['KontaktImePrezime'] = this.kontaktImePrezime;
    data['KontaktProdukcija'] = this.kontaktProdukcija;
    data['KontaktTelefon'] = this.kontaktTelefon;
    data['KontaktMobitel'] = this.kontaktMobitel;
    data['KontaktFax'] = this.kontaktFax;
    data['KontaktMail'] = this.kontaktMail;
    data['KontaktWebProdukcija'] = this.kontaktWebProdukcija;
    data['IP'] = this.iP;
    data['ID'] = this.iD;
    data['Pogledan'] = this.pogledan;
    data['Odabran'] = this.odabran;
    data['Zanimljiv'] = this.zanimljiv;
    data['KomentarSelektora'] = this.komentarSelektora;
    data['FestivaliNagrade'] = this.festivaliNagrade;
    data['FestivaliNagradeEN'] = this.festivaliNagradeEN;
    data['VideoIFrame'] = this.videoIFrame;
    data['DanPrikazivanja'] = this.danPrikazivanja;
    data['RedniBrojPrikazivanja'] = this.redniBrojPrikazivanja;
    data['Fotografija'] = this.fotografija;
    data['KategorijaID'] = this.kategorijaID;
    data['Konkurencija'] = this.konkurencija;
    data['ForspanIFrame'] = this.forspanIFrame;
    return data;
  }
}
